# Generated by Django 5.2.8 on 2025-11-10 22:30

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(db_comment='The name of the kitty')),
                ('age', models.IntegerField(db_comment='The age of the kitty in years')),
                ('weight', models.IntegerField(db_comment='The weight of the kitty in pounds')),
                ('gender', models.TextField(db_comment='The gender of the kitty')),
                ('breed', models.TextField(db_comment='The breed of the kitty')),
                ('color', models.TextField(db_comment='The color/pattern of the kitty')),
                ('image_url', models.URLField(db_comment="URL of the kitty's image on the SFPCA website")),
                ('is_adopted', models.BooleanField(db_comment='Whether the kitty has been adopted', default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.OneToOneField(db_comment='The Django user account associated with this adopter', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kitties', models.ManyToManyField(db_comment='Kitties that this adopter has saved/alerts for', to='kittyalert.kitty')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(db_comment='The name of the shelter')),
                ('slug', models.SlugField(db_comment='The slug of the shelter', unique=True)),
                ('website', models.URLField(db_comment='The website URL of the shelter', max_length=255)),
                ('kitties', models.ManyToManyField(db_comment='Kitties that are available for adoption at this shelter', related_name='shelters', to='kittyalert.kitty')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kitty',
            name='shelter',
            field=models.ForeignKey(db_comment='The shelter where this kitty is available for adoption', on_delete=django.db.models.deletion.CASCADE, to='kittyalert.shelter'),
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.TextField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Successful'), ('failed', 'Failed')], db_comment='Current status of the scrape operation', default='waiting')),
                ('kitties_found', models.IntegerField(db_comment='Total number of kitties found during the scrape', default=0)),
                ('kitties_new', models.IntegerField(db_comment='Number of new kitties discovered in this scrape', default=0)),
                ('error_message', models.TextField(blank=True, db_comment='Error message if the scrape failed', null=True)),
                ('raw_data', models.JSONField(blank=True, db_comment='Raw scraped data stored as JSON for debugging purposes', help_text='Raw scraped data for debugging', null=True)),
                ('shelter', models.ForeignKey(db_comment='The shelter that was scraped', on_delete=django.db.models.deletion.CASCADE, related_name='scrape_runs', to='kittyalert.shelter')),
            ],
            options={
                'indexes': [models.Index(fields=['shelter', 'status'], name='kittyalert__shelter_c7caa0_idx')],
            },
        ),
    ]
