# Generated by Django 5.2.8 on 2025-11-10 22:38

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, db_comment='The slug of the shelter, automatically generated from the name', editable=False, populate_from='name', unique=True),
        ),
    ]
