# Generated by Django 5.2.8 on 2025-11-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0002_alter_shelter_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='website',
            new_name='scrape_url',
        ),
    ]
