# Generated by Django 5.2.8 on 2025-11-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0003_rename_website_shelter_scrape_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitty',
            options={},
        ),
        migrations.RemoveField(
            model_name='kitty',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='scraperun',
            name='error_message',
        ),
        migrations.AddField(
            model_name='kitty',
            name='description',
            field=models.TextField(blank=True, db_comment='The description of the kitty', null=True),
        ),
        migrations.AddField(
            model_name='kitty',
            name='image_urls',
            field=models.JSONField(blank=True, db_comment="The URLs of the kitty's images", null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='error',
            field=models.JSONField(blank=True, db_comment='Error message if the scrape failed', null=True),
        ),
        migrations.AlterField(
            model_name='scraperun',
            name='status',
            field=models.TextField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed')], db_comment='Current status of the scrape operation', default='waiting'),
        ),
        migrations.AddConstraint(
            model_name='kitty',
            constraint=models.UniqueConstraint(fields=('shelter', 'description'), name='unique_kitty_by_description_and_image'),
        ),
    ]
