# Generated by Django 5.2.8 on 2025-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0004_alter_kitty_options_remove_kitty_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitty',
            name='age',
            field=models.TextField(db_comment='The age of the kitty in years'),
        ),
        migrations.AlterField(
            model_name='kitty',
            name='weight',
            field=models.TextField(db_comment='The weight of the kitty in pounds'),
        ),
    ]
