# Generated by Django 5.2.8 on 2025-11-11 19:38

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0005_alter_kitty_age_alter_kitty_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='kitties',
            field=models.ManyToManyField(to='kittyalert.kitty'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='kitties',
            field=models.ManyToManyField(related_name='shelters', to='kittyalert.kitty'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('adopter', models.ForeignKey(db_comment="The adopter that is subscribed to this shelter's kitties", on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='kittyalert.adopter')),
                ('shelter', models.ForeignKey(db_comment='The shelter that is subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='kittyalert.shelter')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
