# Generated by Django 5.2.8 on 2025-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0006_alter_adopter_kitties_alter_shelter_kitties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperun',
            name='error',
        ),
        migrations.RemoveField(
            model_name='scraperun',
            name='kitties_new',
        ),
        migrations.AddField(
            model_name='scraperun',
            name='errors',
            field=models.JSONField(blank=True, db_comment='Errors encountered during the scrape', null=True),
        ),
    ]
