# Generated by Django 5.2.8 on 2025-11-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0007_remove_scraperun_error_remove_scraperun_kitties_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='link',
            field=models.URLField(db_comment="The URL of the kitty's page on the shelter's website", null=True),
        ),
    ]
