# Generated by Django 5.2.8 on 2025-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0008_kitty_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitty',
            name='link',
            field=models.URLField(db_comment="The URL of the kitty's page on the shelter's website", default='https://www.sfspca.org/'),
            preserve_default=False,
        ),
    ]
