# Generated by Django 5.2.8 on 2025-11-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0009_alter_kitty_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='location',
            field=models.TextField(db_comment='The location of the kitty or whether they are bonded with another kitty', default=1),
            preserve_default=False,
        ),
    ]
