# Generated by Django 5.2.8 on 2025-11-14 00:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0010_kitty_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_comment='Phone number for SMS notifications', max_length=128, null=True, region=None),
        ),
    ]
