# Generated by Django 5.2.8 on 2025-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0011_adopter_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='adopter',
            name='email',
            field=models.EmailField(db_comment='The email address of the adopter', default='rosschapman@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
