# Generated by Django 5.2.8 on 2025-11-19 00:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittyalert', '0012_remove_adopter_phone_number_adopter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email_sent_at', models.DateTimeField(blank=True, db_comment='The time the email was sent', null=True)),
                ('errors', models.JSONField(blank=True, db_comment='Errors encountered during the notification', null=True)),
                ('scrape_run', models.ForeignKey(db_comment='The scrape run that was used to send the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kittyalert.scraperun')),
                ('subscription', models.ForeignKey(db_comment='The subscription that was notified', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kittyalert.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['subscription', '-created'], name='kittyalert__subscri_96c5d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'scrape_run'), name='unique_notification_by_subscription_and_scrape_run')],
            },
        ),
    ]
